version: '3.8'

services:
  bot:
    build: 
      context: bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=False
    networks:
      - ulocation-network

  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - UPLOAD_DIR=/app/uploads
    networks:
      - ulocation-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - ulocation-network

networks:
  ulocation-network:
    driver: bridge
